-- Membership 全量重构（PostgreSQL，非兼容）
-- 目标：
-- 1) 角色管范围，会员管资格，权益管能力
-- 2) 支持 VIP/SVIP 各 1~10 级
-- 3) 支持经验条升级（exp_required 阈值）

BEGIN;

DROP TABLE IF EXISTS membership_tier_entitlement;
DROP TABLE IF EXISTS membership_entitlement;
DROP TABLE IF EXISTS membership_record;
DROP TABLE IF EXISTS membership_user;
DROP TABLE IF EXISTS membership_plan;
DROP TABLE IF EXISTS membership_tier;

CREATE TABLE membership_tier
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_code  VARCHAR(16)              NOT NULL,
    code         VARCHAR(32)              NOT NULL,
    name         VARCHAR(64)              NOT NULL,
    grade        SMALLINT                 NOT NULL DEFAULT 0,
    exp_required INTEGER                  NOT NULL DEFAULT 0,
    weight       SMALLINT                 NOT NULL,
    sort         INTEGER                  NOT NULL DEFAULT 0,
    is_default   BOOLEAN                  NOT NULL DEFAULT FALSE,
    status       SMALLINT                 NOT NULL DEFAULT 1,
    description  TEXT,
    created_time TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ
);

ALTER TABLE membership_tier
    ADD CONSTRAINT uq_membership_tier_code UNIQUE (code),
    ADD CONSTRAINT uq_membership_tier_weight UNIQUE (weight),
    ADD CONSTRAINT uq_membership_tier_family_grade UNIQUE (family_code, grade),
    ADD CONSTRAINT ck_membership_tier_status CHECK (status IN (0, 1));

CREATE INDEX idx_membership_tier_status_sort ON membership_tier (status, sort);

COMMENT ON TABLE membership_tier IS '会员等级表';
COMMENT ON COLUMN membership_tier.family_code IS '等级族群(FREE/VIP/SVIP)';
COMMENT ON COLUMN membership_tier.grade IS '族群内等级';
COMMENT ON COLUMN membership_tier.exp_required IS '达到该等级所需经验';

INSERT INTO membership_tier (family_code, code, name, grade, exp_required, weight, sort, is_default, status, description)
VALUES ('FREE', 'FREE-0', '免费', 0, 0, 0, 0, TRUE, 1, '默认免费等级');

INSERT INTO membership_tier (family_code, code, name, grade, exp_required, weight, sort, is_default, status, description)
SELECT 'VIP',
       'VIP-' || g::text,
       'VIP' || g::text,
       g,
       (g - 1) * 100,
       100 + g,
       100 + g,
       FALSE,
       1,
       'VIP 等级'
FROM generate_series(1, 10) AS g;

INSERT INTO membership_tier (family_code, code, name, grade, exp_required, weight, sort, is_default, status, description)
SELECT 'SVIP',
       'SVIP-' || g::text,
       'SVIP' || g::text,
       g,
       (g - 1) * 200,
       200 + g,
       200 + g,
       FALSE,
       1,
       'SVIP 等级'
FROM generate_series(1, 10) AS g;

CREATE TABLE membership_plan
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(64)              NOT NULL,
    tier_id        BIGINT                   NOT NULL,
    role_id        BIGINT                   NOT NULL,
    duration_days  INTEGER                  NOT NULL,
    price          INTEGER                  NOT NULL DEFAULT 0,
    original_price INTEGER                  NOT NULL DEFAULT 0,
    description    TEXT,
    sort           INTEGER                  NOT NULL DEFAULT 0,
    status         SMALLINT                 NOT NULL DEFAULT 1,
    created_time   TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    updated_time   TIMESTAMPTZ
);

ALTER TABLE membership_plan
    ADD CONSTRAINT uq_membership_plan_name UNIQUE (name),
    ADD CONSTRAINT ck_membership_plan_status CHECK (status IN (0, 1)),
    ADD CONSTRAINT fk_membership_plan_tier
        FOREIGN KEY (tier_id) REFERENCES membership_tier (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_membership_plan_role
        FOREIGN KEY (role_id) REFERENCES sys_role (id) ON DELETE RESTRICT;

CREATE INDEX idx_membership_plan_tier_status ON membership_plan (tier_id, status);
CREATE INDEX idx_membership_plan_role_status ON membership_plan (role_id, status);

COMMENT ON TABLE membership_plan IS '会员计划表';

CREATE TABLE membership_user
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT                   NOT NULL,
    family_code  VARCHAR(16)              NOT NULL,
    tier_id      BIGINT                   NOT NULL,
    tier_code    VARCHAR(32)              NOT NULL,
    tier_name    VARCHAR(64)              NOT NULL,
    tier_grade   SMALLINT                 NOT NULL DEFAULT 0,
    tier_weight  SMALLINT                 NOT NULL,
    exp          INTEGER                  NOT NULL DEFAULT 0,
    valid_from   TIMESTAMPTZ,
    valid_to     TIMESTAMPTZ,
    source       VARCHAR(32)              NOT NULL DEFAULT 'admin',
    source_key   VARCHAR(64),
    status       SMALLINT                 NOT NULL DEFAULT 1,
    remark       TEXT,
    created_time TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ
);

ALTER TABLE membership_user
    ADD CONSTRAINT uq_membership_user_family UNIQUE (user_id, family_code),
    ADD CONSTRAINT ck_membership_user_status CHECK (status IN (0, 1, 2)),
    ADD CONSTRAINT fk_membership_user_tier
        FOREIGN KEY (tier_id) REFERENCES membership_tier (id) ON DELETE RESTRICT;

CREATE INDEX idx_membership_user_active ON membership_user (user_id, status, valid_to);
CREATE INDEX idx_membership_user_family_status ON membership_user (family_code, status);

COMMENT ON TABLE membership_user IS '用户会员状态表';

CREATE TABLE membership_record
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT                   NOT NULL,
    family_code     VARCHAR(16)              NOT NULL,
    tier_id         BIGINT                   NOT NULL,
    plan_id         BIGINT,
    op_type         VARCHAR(16)              NOT NULL DEFAULT 'grant',
    days            INTEGER                  NOT NULL DEFAULT 0,
    exp_delta       INTEGER                  NOT NULL DEFAULT 0,
    source          VARCHAR(32)              NOT NULL,
    source_key      VARCHAR(64)              NOT NULL,
    source_detail   VARCHAR(256),
    valid_to_before TIMESTAMPTZ,
    valid_to_after  TIMESTAMPTZ,
    remark          TEXT,
    created_time    TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    updated_time    TIMESTAMPTZ
);

ALTER TABLE membership_record
    ADD CONSTRAINT uq_membership_record_idempotent
        UNIQUE (user_id, family_code, source, source_key, op_type),
    ADD CONSTRAINT fk_membership_record_tier
        FOREIGN KEY (tier_id) REFERENCES membership_tier (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_membership_record_plan
        FOREIGN KEY (plan_id) REFERENCES membership_plan (id) ON DELETE SET NULL;

CREATE INDEX idx_membership_record_user_created ON membership_record (user_id, created_time DESC);
CREATE INDEX idx_membership_record_source ON membership_record (source, source_key);
CREATE INDEX idx_membership_record_family_created ON membership_record (family_code, created_time DESC);

COMMENT ON TABLE membership_record IS '会员发放流水表';

CREATE TABLE membership_entitlement
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(64)              NOT NULL,
    name          VARCHAR(64)              NOT NULL,
    value_type    VARCHAR(16)              NOT NULL DEFAULT 'bool',
    default_value INTEGER                  NOT NULL DEFAULT 0,
    sort          INTEGER                  NOT NULL DEFAULT 0,
    status        SMALLINT                 NOT NULL DEFAULT 1,
    description   TEXT,
    created_time  TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    updated_time  TIMESTAMPTZ
);

ALTER TABLE membership_entitlement
    ADD CONSTRAINT uq_membership_entitlement_code UNIQUE (code),
    ADD CONSTRAINT ck_membership_entitlement_status CHECK (status IN (0, 1));

CREATE INDEX idx_membership_entitlement_status_sort ON membership_entitlement (status, sort);

COMMENT ON TABLE membership_entitlement IS '会员权益定义表';

CREATE TABLE membership_tier_entitlement
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_id          BIGINT                   NOT NULL,
    entitlement_id   BIGINT                   NOT NULL,
    entitlement_code VARCHAR(64)              NOT NULL,
    value            INTEGER                  NOT NULL DEFAULT 1,
    status           SMALLINT                 NOT NULL DEFAULT 1,
    description      TEXT,
    created_time     TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    updated_time     TIMESTAMPTZ
);

ALTER TABLE membership_tier_entitlement
    ADD CONSTRAINT uq_membership_tier_entitlement UNIQUE (tier_id, entitlement_id),
    ADD CONSTRAINT ck_membership_tier_entitlement_status CHECK (status IN (0, 1)),
    ADD CONSTRAINT fk_membership_tier_entitlement_tier
        FOREIGN KEY (tier_id) REFERENCES membership_tier (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_membership_tier_entitlement_entitlement
        FOREIGN KEY (entitlement_id) REFERENCES membership_entitlement (id) ON DELETE CASCADE;

CREATE INDEX idx_membership_tier_entitlement_tier ON membership_tier_entitlement (tier_id, status);
CREATE INDEX idx_membership_tier_entitlement_code ON membership_tier_entitlement (entitlement_code, status);

COMMENT ON TABLE membership_tier_entitlement IS '等级权益映射表';

COMMIT;
