CREATE TABLE IF NOT EXISTS sys_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_type VARCHAR(32) NOT NULL DEFAULT 'other',
    content TEXT NOT NULL,
    contact VARCHAR(128),
    images JSONB,
    source_app VARCHAR(32),
    source_platform VARCHAR(32),
    page_path VARCHAR(512),
    target_type VARCHAR(32),
    target_id VARCHAR(64),
    target_text VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    reply_content TEXT,
    read_time TIMESTAMPTZ,
    handled_by BIGINT,
    handled_time TIMESTAMPTZ,
    ip_address VARCHAR(64),
    user_agent VARCHAR(512),
    created_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_feedback_status_created
    ON sys_feedback (status, created_time DESC);

CREATE INDEX IF NOT EXISTS idx_feedback_source
    ON sys_feedback (source_app, source_platform);

CREATE INDEX IF NOT EXISTS idx_feedback_target
    ON sys_feedback (target_type, target_id);

DROP TABLE IF EXISTS gk_feedback;
