CREATE TABLE IF NOT EXISTS `agent_run` (
  `id` BIGINT NOT NULL,
  `agent_key` VARCHAR(64) NOT NULL,
  `agent_version` VARCHAR(32) NOT NULL,
  `workflow_key` VARCHAR(64) NOT NULL,
  `workflow_version` VARCHAR(32) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `subject_type` VARCHAR(64) NOT NULL,
  `subject_id` BIGINT NOT NULL,
  `idempotency_key` VARCHAR(160) NOT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'queued',
  `stage` VARCHAR(64) NULL,
  `progress` FLOAT NOT NULL DEFAULT 0,
  `input_snapshot` JSON NOT NULL,
  `result_summary` LONGTEXT NULL,
  `result_payload` JSON NULL,
  `config_snapshot` JSON NOT NULL,
  `error_code` VARCHAR(64) NULL,
  `error_message` LONGTEXT NULL,
  `started_time` DATETIME NULL,
  `finished_time` DATETIME NULL,
  `created_time` DATETIME NOT NULL,
  `updated_time` DATETIME NULL,
  `deleted` BIGINT NOT NULL DEFAULT 0,
  `deleted_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_agent_run_idempotency_key` (`idempotency_key`),
  KEY `idx_agent_run_user_status` (`user_id`, `status`, `created_time`),
  KEY `idx_agent_run_subject` (`subject_type`, `subject_id`, `created_time`)
  ,CONSTRAINT `fk_agent_run_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `agent_run_step` (
  `id` BIGINT NOT NULL,
  `run_id` BIGINT NOT NULL,
  `step_no` INT NOT NULL,
  `node_key` VARCHAR(64) NOT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'running',
  `input_snapshot` JSON NOT NULL,
  `output_snapshot` JSON NULL,
  `model_name` VARCHAR(128) NULL,
  `tokens_in` INT NOT NULL DEFAULT 0,
  `tokens_out` INT NOT NULL DEFAULT 0,
  `duration_ms` INT NOT NULL DEFAULT 0,
  `error_message` LONGTEXT NULL,
  `started_time` DATETIME NULL,
  `finished_time` DATETIME NULL,
  `created_time` DATETIME NOT NULL,
  `updated_time` DATETIME NULL,
  `deleted` BIGINT NOT NULL DEFAULT 0,
  `deleted_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_agent_run_step_no` (`run_id`, `step_no`),
  KEY `idx_agent_run_step_run` (`run_id`, `step_no`)
  ,CONSTRAINT `fk_agent_run_step_run` FOREIGN KEY (`run_id`) REFERENCES `agent_run` (`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `agent_rubric` (
  `id` BIGINT NOT NULL,
  `agent_key` VARCHAR(64) NOT NULL,
  `question_id` BIGINT NOT NULL,
  `reference_set_hash` VARCHAR(64) NOT NULL,
  `source_hash` VARCHAR(64) NOT NULL,
  `rubric_version` VARCHAR(64) NOT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'ready',
  `provider` VARCHAR(128) NULL,
  `model_name` VARCHAR(128) NULL,
  `rubric_payload` JSON NOT NULL,
  `error_message` LONGTEXT NULL,
  `created_time` DATETIME NOT NULL,
  `updated_time` DATETIME NULL,
  `deleted` BIGINT NOT NULL DEFAULT 0,
  `deleted_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_agent_rubric_source`
    (`agent_key`, `question_id`, `reference_set_hash`, `source_hash`, `rubric_version`),
  KEY `idx_agent_rubric_question` (`agent_key`, `question_id`, `status`)
);

CREATE TABLE IF NOT EXISTS `agent_grading_feedback` (
  `id` BIGINT NOT NULL,
  `run_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `question_id` BIGINT NOT NULL,
  `point_key` VARCHAR(80) NOT NULL,
  `scope` VARCHAR(16) NOT NULL DEFAULT 'report',
  `corrected_status` VARCHAR(16) NOT NULL,
  `corrected_quote` LONGTEXT NOT NULL,
  `note` LONGTEXT NOT NULL,
  `before_snapshot` JSON NOT NULL,
  `after_snapshot` JSON NOT NULL,
  `created_time` DATETIME NOT NULL,
  `updated_time` DATETIME NULL,
  `deleted` BIGINT NOT NULL DEFAULT 0,
  `deleted_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_agent_grading_feedback_point` (`run_id`, `point_key`, `scope`),
  KEY `idx_agent_grading_feedback_question` (`question_id`, `scope`, `created_time`),
  CONSTRAINT `fk_agent_grading_feedback_run` FOREIGN KEY (`run_id`) REFERENCES `agent_run` (`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `agent_calibration_anchor` (
  `id` BIGINT NOT NULL,
  `agent_key` VARCHAR(64) NOT NULL,
  `bank_revision_id` BIGINT NOT NULL,
  `session_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `actual_score_percent` DECIMAL(7,3) NOT NULL,
  `predicted_score_percent` DECIMAL(7,3) NOT NULL,
  `actual_total_score` DECIMAL(10,3) NOT NULL,
  `predicted_total_score` DECIMAL(10,3) NOT NULL,
  `paper_total_score` DECIMAL(10,3) NOT NULL,
  `source_type` VARCHAR(32) NOT NULL,
  `source_hash` VARCHAR(64) NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'ready',
  `exclusion_reason` LONGTEXT NULL,
  `metadata_payload` JSON NOT NULL,
  `created_time` DATETIME NOT NULL,
  `updated_time` DATETIME NULL,
  `deleted` BIGINT NOT NULL DEFAULT 0,
  `deleted_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_agent_calibration_anchor_session` (`agent_key`, `session_id`),
  KEY `idx_agent_calibration_anchor_ready` (`agent_key`, `status`, `bank_revision_id`),
  KEY `idx_agent_calibration_anchor_session` (`session_id`, `created_time`)
);

CREATE TABLE IF NOT EXISTS `agent_calibration_policy` (
  `id` BIGINT NOT NULL,
  `agent_key` VARCHAR(64) NOT NULL,
  `policy_version` VARCHAR(64) NOT NULL,
  `scope_type` VARCHAR(24) NOT NULL,
  `scope_key` VARCHAR(160) NOT NULL,
  `active_key` VARCHAR(192) NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `anchor_count` INT NOT NULL DEFAULT 0,
  `paper_count` INT NOT NULL DEFAULT 0,
  `source_hash` VARCHAR(64) NOT NULL,
  `policy_payload` JSON NOT NULL,
  `metrics_payload` JSON NOT NULL,
  `created_time` DATETIME NOT NULL,
  `updated_time` DATETIME NULL,
  `deleted` BIGINT NOT NULL DEFAULT 0,
  `deleted_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_agent_calibration_policy_source` (`agent_key`, `source_hash`),
  UNIQUE KEY `uq_agent_calibration_policy_active` (`agent_key`, `active_key`),
  KEY `idx_agent_calibration_policy_scope` (`agent_key`, `scope_type`, `scope_key`, `status`)
);
